credentials:
  usernames:
    jsmith:
      email: danie.theron@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Danie Theron
      password: Deadly2328 # Will be hashed automatically
cookie:
  expiry_days: 30
  key: hfdysoHDHAbakPPiat # Must be string
  name: aficionado
pre-authorized:
  emails:
  - danie.theron@gmail.com